name: draftbit/ui

on:
  push:
    branches:
      - master
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  typecheck:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
        working-directory: packages/react-native-jigsaw

      - name: Type check
        run: yarn typescript
        working-directory: packages/react-native-jigsaw

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      # https://github.com/actions/cache/blob/main/examples.md#node---yarn
      - name: Restore node_modules cache
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit`
        with:
          path: "**/node_modules"
          key: node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install monorepo dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
        working-directory: packages/react-native-jigsaw

      - name: Build
        run: yarn build
        working-directory: packages/react-native-jigsaw
  testcollector:
    name: Test Collector Script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      # https://github.com/actions/cache/blob/main/examples.md#node---yarn
      - name: Restore node_modules cache
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit`
        with:
          path: "**/node_modules"
          key: node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
        working-directory: packages/react-native-jigsaw

      - name: Test collector script
        run: |
          npx json-server --port 3001 mock-backend.json & export JSON_SERVER_PID=$!;
          sleep 2;
          node scripts/collector.js;
          kill $JSON_SERVER_PID;
          [[ $(jq '.components | length' mock-backend.json) > 0 ]] || exit 1;
        working-directory: packages/react-native-jigsaw
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      # https://github.com/actions/cache/blob/main/examples.md#node---yarn
      - name: Restore node_modules cache
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit`
        with:
          path: "**/node_modules"
          key: node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
        working-directory: packages/react-native-jigsaw

      - name: Release next to NPM
        id: release_candidate_version
        if: github.event_name == 'pull_request'
        run: |
          npm config set //registry.npmjs.org/:_authToken $NODE_AUTH_TOKEN
          npm version prerelease --preid rc$(git rev-parse --short HEAD) -no-git-tag-version
          npm publish --access public --tag next --verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.JIGSAW_AUTH_TOKEN }}
        working-directory: packages/react-native-jigsaw

      - name: Release to NPM
        if: github.event_name != 'pull_request'
        run: |
          npm config set //registry.npmjs.org/:_authToken $NODE_AUTH_TOKEN
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.JIGSAW_AUTH_TOKEN }}
        working-directory: packages/react-native-jigsaw

      - name: Release to Snack
        run: |
          export version=$(jq -r .version package.json);
          sleep 10
          curl "https://snackager.expo.io/bundle/@draftbit/ui@"$version"?version_snackager=true&platforms=ios,android,web&bypassCache=true";
        working-directory: packages/react-native-jigsaw

      - name: Add comment to PR
        if: github.event_name == 'pull_request'
        env:
          URL: ${{ github.event.pull_request.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(npm view @draftbit/ui dist-tags.next);
          curl -X POST $URL \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data "{ \"body\": \"Published version: [@draftbit/ui@$VERSION](https://www.npmjs.com/package/@draftbit/ui/v/$VERSION)\" }"
